spring:
    profiles:
        active: dev
---
# 开发环境    ---：文档块
spring:
    profiles: dev
    application: 
        name: ins-cola
    aop: 
        auto: true
    datasource:
        url: jdbc:mysql://localhost:3306/ins-cola-test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&autoReconnect=true
        username: root
        password: dinqin..
        driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
        host: 122.51.15.106
        password: 123456
        port: 6379  
        database: 1
        pool:
            max-active: 8
            max-wait: -1
            max-idle: 10
            min-idle: 0
        timeout: 15000
server:
    port: 8888
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: cont=countSql
    page-size-zero: true
# 七牛云配置
qiniu:
    AK: NC-K-4dLAUWp-ohw7FdCOUULtBHdgKYJ1Koo9d1Y
    SK: EXrmWjC_-tK2FODe1iyS25M1FhQSOn_9eGsJbAXt
# 小程序配置
wx:
    qe:
        appid: wx5b484b45745a47d3
        appsecret: 699c9d167705475a59c2ec338467e03e
        modelId: 9_BkwwFE-R8D0ymqVFRXezkXb5EFO4pitu3ZqJC7r-0
# 阿里云配置
ali:
    accessKeyId: LTAI4FqU3i4Zy2Uu4AraQb8a
    accessKeySecret: IDFwQsOiVL12Jexh7nEFGH1xlipJwT
    templateCode: SMS_183240580
    signName: CloudAPI社区
# 日志级别
logging:
    level:
        com:
            baoyun:
                ins:
                    mapper: DEBUG
---
# 生产环境
spring:
    profiles: prod
    application: 
        name: ins-cola
    aop: 
        auto: true
    # 生产环境
    datasource:
        url: jdbc:mysql://122.51.15.106:3306/ins-cola-test?useUnicode=true&characterEncoding=utf-8&serverTimezone=CST&autoReconnect=true
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
        host: 122.51.15.106
        password: 123456
        port: 6379  
        database: 1
        pool:
            max-active: 8
            max-wait: -1
            max-idle: 10
            min-idle: 0
        timeout: 15000
server:
    port: 8888
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: cont=countSql
    page-size-zero: true
# 七牛云配置
qiniu:
    AK: NC-K-4dLAUWp-ohw7FdCOUULtBHdgKYJ1Koo9d1Y
    SK: EXrmWjC_-tK2FODe1iyS25M1FhQSOn_9eGsJbAXt
# 小程序配置
wx:
    qe:
        appid: wx5b484b45745a47d3
        appsecret: 699c9d167705475a59c2ec338467e03e
        modelId: 9_BkwwFE-R8D0ymqVFRXezkXb5EFO4pitu3ZqJC7r-0
# 阿里云配置
ali:
    accessKeyId: LTAI4FqU3i4Zy2Uu4AraQb8a
    accessKeySecret: IDFwQsOiVL12Jexh7nEFGH1xlipJwT
    templateCode: SMS_183240580
    signName: CloudAPI社区
# 日志级别
logging:
    level:
        com:
            baoyun:
                ins:
                    mapper: DEBUG
---
# docker --link环境
spring:
    profiles: docker
    application: 
        name: ins-cola
    aop: 
        auto: true
    datasource:
        url: jdbc:mysql://mysql:3306/ins-cola-test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&autoReconnect=true
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
        host: 122.51.15.106
        password: 123456
        port: 6379  
        database: 1
        pool:
            max-active: 8
            max-wait: -1
            max-idle: 10
            min-idle: 0
        timeout: 15000
server:
    port: 80
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: cont=countSql
    page-size-zero: true
# 七牛云配置
qiniu:
    AK: NC-K-4dLAUWp-ohw7FdCOUULtBHdgKYJ1Koo9d1Y
    SK: EXrmWjC_-tK2FODe1iyS25M1FhQSOn_9eGsJbAXt
# 小程序配置
wx:
    qe:
        appid: wx5b484b45745a47d3
        appsecret: 699c9d167705475a59c2ec338467e03e
        modelId: 9_BkwwFE-R8D0ymqVFRXezkXb5EFO4pitu3ZqJC7r-0
# 阿里云配置
ali:
    accessKeyId: LTAI4FqU3i4Zy2Uu4AraQb8a
    accessKeySecret: IDFwQsOiVL12Jexh7nEFGH1xlipJwT
    templateCode: SMS_183240580
    signName: CloudAPI社区
# 日志级别
logging:
    level:
        com:
            baoyun:
                ins:
                    mapper: DEBUG